namespace ReverseStruct.StaticCode.Crumbs;

public static class FileCrumbs
{
    public const string Header = $@"//
// <auto-generated>
// This is auto-generated code created by {LibraryConstants.LibraryName} (version = {LibraryConstants.LibraryVersion})
// Please don't touch!
// </auto-generated>
//
";
}